config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  resources :chats, only: %i[index create show update] do
    post 'chat', on: :member
  end

  resource :search, only: %i[show]

  resource :settings, only: %i[show update] do
    post 'resync', on: :collection
  end

  # Devise User Paths
  devise_for :users,
             path: '',
             skip: %i[registrations passwords],
             path_names: {
               sign_in: 'start',
               sign_out: 'logout'
             },
             controllers: {
               sessions: 'users/sessions'
             }

  # Omniauth Callbacks
  devise_scope :user do
    get '/auth/google_oauth2/callback', to: 'users/omniauth_callbacks#google_oauth2', as: :omniauth_callback
  end

  match '/auth/:provider', via: %i[post], as: :auth_provider, to: 'auth#create'
  scope '/_/permissions' do
    get '/google_with_google_drive/callback', to: 'auth#handle_google_callback'
    get '/google_with_gmail/callback', to: 'auth#handle_google_callback'
  end

  # Defines the root path route ("/")
  root 'searches#show'
end

app/controllers/searches_controller.rb
# frozen_string_literal: true

class SearchesController < ApplicationController
  def show
    return unless params[:q].present?

    perform_search
    render :results
  end

  private

  def perform_search
    @query_id = SecureRandom.uuid
    PerformSearchJob.perform_later(params[:q], current_user, @query_id)

    # TODO: Should the default be to search by embedding? Generating an embedding for the query makes it slow.
    #       We could alternately do full-text search, but this would mean we need to un-encrypt the chunk content.
    embedding = EmbeddingService.generate(params[:q])
    @documents = Document.search_by_chunks(embedding, current_user.documents).limit(10)
  end
end

app/helpers/search_helper.rb
# frozen_string_literal: true

module SearchHelper
end

app/helpers/searches_helper.rb
# frozen_string_literal: true

module SearchesHelper
  def link_to_gmail_message(message_id)
    base = URI("https://mail.google.com/mail/#inbox/#{message_id}")
    base.query = URI.encode_www_form(authuser: current_user.email)
    base.to_s
  end
end

app/views/searches/create.turbo_stream.erb
<%= turbo_stream.replace :query_results do %>
  <%= turbo_stream_from @query_id %>

  <div id="query_results" class="">
    <div id="generative_summary" class="w-full border rounded bg-white prose px-6 py-4 text-sm max-h-96 overflow-y-auto">
      Loading...
    </div>
  </div>
<% end %>

app/views/searches/results.html.erb
<div class="py-4 overflow-y-auto">
  <div class="flex flex-col justify-center items-center gap-2 mx-auto max-w-2xl">

    <%= form_with url: search_path, method: :get, class: 'w-full flex justify-center ' do |form| %>
      <div class="border px-3 py-1 bg-white flex items-center grow has-[:focus]:border-stone-400">
        <%= heroicon 'magnifying-glass', options: { class: 'size-4' } %>
        <%= form.text_field :q, value: params[:q], class: 'grow border-0 focus:ring-0' %>
      </div>
    <% end %>

  </div>

  <div class="bg-stone-100 w-full my-4 border-y">
    <div class="max-w-2xl mx-auto">
      <%= render Search::ResultsComponent.new(query_id: @query_id) %>
    </div>
  </div>

  <div class="max-w-2xl mx-auto flex flex-col gap-2">
    <% @documents.each do |document| %>
      <%= render "searches/results/#{document.documentable_name}", document: %>
    <% end %>
  </div>
</div>

app/views/searches/show.html.erb
<div class="mt-32">
  <div class="flex flex-col justify-center items-center gap-2 max-w-xl mx-auto">

    <%= form_with url: search_path, method: :get, class: 'w-full flex justify-center max-w-xl' do |form| %>
      <div class="border px-3 py-1 bg-white flex items-center grow has-[:focus]:border-stone-400 border-stone-300">
        <%= heroicon 'magnifying-glass', options: { class: 'size-4' } %>
        <%= form.text_field :q, class: 'grow border-0 focus:ring-0', autofocus: true %>
      </div>
    <% end %>

    <div class="text-xs text-stone-500 flex flex-col gap-2">
      <% if current_user.documents.count > 0 %>
        <%= delimited_pluralized(current_user.documents.count, 'document') %> indexed
      <% else %>
        No documents indexed yet, start by <%= link_to 'adding an integration', settings_path, class: 'underline' %>
      <% end %>

      <div class="flex justify-center items-center gap-2 max-w-xl mx-auto">
        <% if current_user.gmail_permission_granted? %>
          <%= image_tag 'search/gmail.svg', class: 'size-4' %>
        <% end %>
        <% if current_user.google_docs_permission_granted? %>
          <%= image_tag 'search/google_docs.png', class: 'h-4' %>
        <% end %>
      </div>
    </div>
  </div>
</div>