config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  resources :chats, only: %i[index create show update] do
    post 'chat', on: :member
  end

  resource :search, only: %i[show]

  resource :settings, only: %i[show update] do
    post 'resync', on: :collection
  end

  # Devise User Paths
  devise_for :users,
             path: '',
             skip: %i[registrations passwords],
             path_names: {
               sign_in: 'start',
               sign_out: 'logout'
             },
             controllers: {
               sessions: 'users/sessions'
             }

  # Omniauth Callbacks
  devise_scope :user do
    get '/auth/google_oauth2/callback', to: 'users/omniauth_callbacks#google_oauth2', as: :omniauth_callback
  end

  match '/auth/:provider', via: %i[post], as: :auth_provider, to: 'auth#create'
  scope '/_/permissions' do
    get '/google_with_google_drive/callback', to: 'auth#handle_google_callback'
    get '/google_with_gmail/callback', to: 'auth#handle_google_callback'
  end

  # Defines the root path route ("/")
  root 'searches#show'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatting</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>

  <body>
    <main class="h-screen flex flex-col"
          data-controller="application">
      <div class="flex-1 flex flex-col h-full"><%= content_for?(:content) ? content_for(:content) : yield %></div>
    </main>
  </body>
</html>

app/views/layouts/authenticated.html.erb
<% content_for :content do %>
  <div class="flex flex-col">
    <div class="flex justify-between pl-4 pr-2 py-2 border-b items-center h-12">
      <div>
        <span class="font-serif font-medium text-stone-700 text-lg">Raggle</span> <span class="text-xs text-stone-500">by Context.ai</span>
      </div>

      <div class="right text-xs flex items-center gap-2 h-8">
        <%= link_to chats_path, class: 'text-stone-600 border py-1 px-2 hover:border-b-2 border-stone-300',
                    data: { action: 'keydown.meta+k@window->application#navigate', 'application-location-param': chats_path } do %>
          + New Chat <span class="bg-stone-200 p-0.5">⌘K</span>
        <% end %>

        <div class="size-6">
          <%= button_to destroy_user_session_path, method: :delete do %>
            <%= profile_picture_tag %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="flex items-stretch grow min-h-0">
    <div class="h-full border-r flex flex-col items-center gap-2 py-1 justify-between bg-white px-1">
      <div class="flex flex-col gap-2">
        <%= render Ui::SidebarNavigationIconComponent.new(
          icon: 'magnifying-glass',
          path: search_path,
          root: true
        ) %>

        <%= render Ui::SidebarNavigationIconComponent.new(
          icon: :users,
          path: chats_path
        ) %>
      </div>
      <%= render Ui::SidebarNavigationIconComponent.new(
        icon: :cog,
        path: settings_path
      ) %>
    </div>
    <div class="w-full h-full overflow-y-auto bg-white">
      <%= yield %>
    </div>
  </div>
<% end %>
<%= render template: 'layouts/application' %>